print(" ")
nome = input("Digite o nome do aluno: ")
disciplina = input("Digite a disciplina: ")
faltas = int(input("Digite a quantidade de faltas: "))
nota = float(input("Digite a nota: "))
print(" ")
print("------------------------------")
print(f'Ficha do aluno: {nome}')
print(f'Disciplina: {disciplina}')
print(f'Faltas: {faltas}')
print(f'Nota: {nota:.2f}')
print("------------------------------")
